In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#Echauffement

a = np.array([1, 2, 3])

#1) a[:,None] est de format (1,3), et a[:,None] de format (3,1) (On rajoute une dimension là où est le None).
#2) a[:,None]-a[None,:] est de format (3,3). En notant a_i le i-ème élément de a, on a alors que l'élément [i,j] est a_i-a_j.

b=np.array([[1,2,3],[4,5,6]])

#3) b[:,None,:] est de format (2,1,3), et b[:,:,None] est de format (2,3,1) (en terme de dimensions, on insère un 1 à l'emplacement du None). 
#D'après les règles du broadcasting, cela implique que leur différence est de format (2,3,3). De plus, en notant b_ij l'élément sur la ligne i, colonne j de b, on a que l'élément [i,j,k] de b[:, None, :] - b[:, :, None] vaut : b_ij-b_ik. 



[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


In [ ]:
#Initialisation aléatoire

# les bornes pour le tirage au sort initial
mass_max = 3.
    
x_min, x_max = -10., 10.
y_min, y_max = -10., 10.

speed_max = 1.

def init_problem(N):
    masses=np.random.uniform(0.01*mass_max,mass_max,N)
    positions=np.random.uniform(np.array([[x_min], [x_max]]),np.array([[y_min], [y_max]]), (2,N))
    speeds=np.random.uniform(np.array([[0.01*speed_max],[speed_max]]),np.array([[0.01*speed_max],[speed_max]]), (2,N))
    return np.array(masses),positions,speeds

# pour tester

# normalement vous devez pouvoir faire ceci

masses, positions, speeds = init_problem(10)

# et ceci devrait afficher OK
try:
    assert masses.shape == (10,) and positions.shape == speeds.shape == (2, 10)
    print("OK")
except:
    print("KO")



OK


In [ ]:
# for your convenience

def init3():
    # first element is sun-like: heavy, at the center, and no speed
    masses = np.array([3, 1, 1], dtype=float)
    positions = np.array([
        [0, 5, -5], 
        [0, 1, -1]], dtype=float)
    speeds = np.array([
        [0, -1, 1], 
        [0, 0, 0]], dtype=float)
    return masses, positions, speeds



In [ ]:
def forces(masses,positions,G=1.0):
    diff=positions[:,None,:]-positions[:,:,None] #comme dans l'échauffement
    distance=np.linalg(diff, axis=2) #On calcule les distances selon la dimension possédant deux éléments (elle est numérotée 2, car diff est de taille (2,N,N), et on numérote de droite à gauche. On considère qu'on enrichit un objet en l'entourant, et non en le remplissant).

